### ISSUE TITLE
Plugin unable to load

### ISSUE THREAD

**Issue by MotherShip808** [ldesgoui/tf2-comp-fixes#18]
`L 04/30/2020 - 22:41:11: [SM] Unable to load extension "dhooks.ext": Could not find interface: ISourceMod
L 04/30/2020 - 22:41:11: [SM] Failed to load plugin "tf2-comp-fixes.smx": Unable to load plugin (no debug string table).`

Getting that error in console. I already left an issue on the dhooks github regarding their issue. unsure of if/when it will be resolved. I am also unsure if that may be causing the plugin to fail to load, but figured I should bring it up regardless.

**Comment by stephanieLGBT** [comment]
update your sourcemod to latest (1.10)

**Comment by MotherShip808** [comment]
> update your sourcemod to latest (1.10)

SourceMod Version Information:
SourceMod Version: 1.9.0.6281
SourcePawn Engine: 1.9.0.6281, jit-x86 (build 1.9.0.6281)
SourcePawn API: v1 = 4, v2 = 12
Compiled on: May 14 2019 16:03:05
Built from: alliedmodders/sourcemod@c5efe48
Build ID: 6281:c5efe48

**Comment by ldesgoui** [comment]
or use the DHooks2 build that supports versions lower than 1.10 (the one without smm-110 in the name)

**Comment by MotherShip808** [comment]
After playing with it for a few days, changing the sourcemod version, changing the dhooks version, the issue was that the machine the servers are intsalled on are windows machines, which is why the plugin wouldnt load.
