### ISSUE TITLE
Sniper prevents jumping after a shot

### ISSUE THREAD

**Issue by coretf** [ldesgoui/tf2-comp-fixes#26]
Would be cool to see but super backburner, keep up the good work pal.

**Comment by ldesgoui** [comment]
Can you explain what this entails?

**Comment by coretf** [comment]
Essentially restoring the ability to jump out of the sniper scope that was removed by Valve many years ago now, at the time it was seen as somewhat strong but all it has encouraged is second scoping, but either way it's fine.

**Comment by ldesgoui** [comment]
Actually, I don't disagree with the change, and won't be implementing it, sorry
