### ISSUE TITLE
Plugin failing to load. v2

### ISSUE THREAD

**Issue by MotherShip808** [ldesgoui/tf2-comp-fixes#37]
A continuation of https://github.com/ldesgoui/tf2-comp-fixes/issues/18

`[SM] Failed to load plugin "tf2-comp-fixes.smx": Unable to load plugin (no debug string table).`

The only solution I could find to this is this forum thread here, detailing that specific issue and why the plugin isnt loading: https://forums.alliedmods.net/showthread.php?t=246405&page=45

And while I agree that just updating soucemod to 1.10 would solve this, current most of the 1-click sourcemod install buttons that most server rentals provide is still on 1.09, including my own host. It can be difficult for people to manually install it as I already failed to install it twice thus far. I am going to be talking to my host about updating their install, however I figured I would bring it up so you were aware.

**Comment by ldesgoui** [comment]
I won't be supporting SourceMod 1.9 but you can use this build which should work for the time being

[tf2-comp-fixes-sm-1.9.zip](https://github.com/ldesgoui/tf2-comp-fixes/files/4650134/tf2-comp-fixes-sm-1.9.zip)

**Comment by MotherShip808** [comment]
Thanks, I appreciate it. If possible, can you add in to the documentation that 1.09 wont be supported, and as such people should upgrade and use the 1.10 version of dhooks2 as well. Once again, appreciate it.
