### ISSUE TITLE
Sticky delay fix cvar is inverted

### ISSUE THREAD

**Issue by bakugo** [ldesgoui/tf2-comp-fixes#42]
When set to 1 it's disabled, when set to 0 it's enabled.

https://github.com/ldesgoui/tf2-comp-fixes/blob/3c6d8d342e76d5cf8e7cd93430a4b9efd44b8f79/scripting/tf2-comp-fixes/fix-sticky-delay.sp#L32-L34

**Comment by ldesgoui** [comment]
fixed in 1.8.2, thanks
