### ISSUE TITLE
Can't get the plugin to work on NFO windows server

### ISSUE THREAD

**Issue by Darshil182** [ldesgoui/tf2-comp-fixes#46]
when I check plugins info it tells me to look at error logs and this is what is in the error logs:

L 10/24/2020 - 11:10:16: [SM] Exception reported: Failed to create detour for CTFGameRules::FlPlayerFallDamage
L 10/24/2020 - 11:10:16: [SM] Blaming: tf2-comp-fixes.smx
L 10/24/2020 - 11:10:16: [SM] Call stack trace:
L 10/24/2020 - 11:10:16: [SM]   [0] SetFailState
L 10/24/2020 - 11:10:16: [SM]   [1] Line 87, addons/sourcemod/scripting/tf2-comp-fixes/common.sp::CheckedDHookCreateFromConf
L 10/24/2020 - 11:10:16: [SM]   [2] Line 6, addons/sourcemod/scripting/tf2-comp-fixes/deterministic-fall-damage.sp::DeterministicFallDamage_Setup
L 10/24/2020 - 11:10:16: [SM]   [3] Line 63, addons/sourcemod/scripting/tf2-comp-fixes.sp::OnPluginStart
L 10/24/2020 - 11:10:16: [SM] Unable to load plugin "tf2-comp-fixes.smx": Error detected in plugin startup (see error logs)

I have tried both the latest version of the plugin and dhooks and even the old version that the rgl server resources ships with.

**Comment by ldesgoui** [comment]
I assume you're the person who contacted me on Discord, my plugin runs on na.serveme.tf NFO servers, I can only assume this is an installation issue, please make sure `tf2-comp-fixes.games.txt` is in the right folder, as that should be the only file needed.

**Comment by ldesgoui** [comment]
Was mistaken, NFO servers on Serveme are Linux, will try to fix this weekend

**Comment by ldesgoui** [comment]
Windows signatures seem to be outdated, if you can spare the time. try with this file in tf/addons/sourcemod/gamedata 
[tf2-comp-fixes.games.txt](https://github.com/ldesgoui/tf2-comp-fixes/files/5469285/tf2-comp-fixes.games.txt) and report to me whether it works or not. I don't have an easy way to test on Windows anymore and it's very time consuming to set it up again, if people can test for me, it would be very much appreciated.

**Comment by Darshil182** [comment]
yep I can do that. I tested and still it doesnt work.

**Comment by ldesgoui** [comment]
If the error message stopped complaining about FlPlayerFallDamage and instead complained about ApplyOnDamageAliveModifyRules, we've made progress, this is another outdated signature, please try with 
[tf2-comp-fixes.games.txt](https://github.com/ldesgoui/tf2-comp-fixes/files/5469965/tf2-comp-fixes.games.txt)

**Comment by ldesgoui** [comment]
fixed in 1.10.3
