### ISSUE TITLE
sm_cf list breaks on old cvar name

### ISSUE THREAD

**Issue by Squidamatron** [ldesgoui/tf2-comp-fixes#58]
https://github.com/ldesgoui/tf2-comp-fixes/blob/216eb8d2efb54d1b7ab6698cd3c90de968977d43/scripting/tf2-comp-fixes.sp#L127

Seems you've missed an older name for `sm_override_pipe_size` while refactoring. Not a giant issue, but it does break the output of `sm_cf list` and `!cf list` by not listing anything beyond `sm_tournament_end_ignores_whitelist`. Calling it over rcon is the only place an exception is visible.

**Comment by ldesgoui** [comment]
Thanks, will fix tonight

**Comment by ldesgoui** [comment]
fixes in v1.11.1
