### ISSUE TITLE
Bad header error while loading plugin

### ISSUE THREAD

**Issue by RoonMoonlight** [ldesgoui/tf2-comp-fixes#59]
Hello, after installing this plugin, the plugin displays an error and fails to load.

```
L 08/28/2021 - 05:51:25: Info (map "pl_cactuscanyon_redux_rc1b") (file "[REDACTED]")
L 08/28/2021 - 05:51:25: [SM] Failed to load plugin "tf2-comp-fixes.smx": Unable to load plugin (bad header).
L 08/28/2021 - 06:03:49: Error log file session closed.
```

Can you fix this issue?

**Comment by ldesgoui** [comment]
What are your metamod:source and sourcemod versions?

**Comment by RoonMoonlight** [comment]
> What are your metamod:source, sourcemod and DHooks versions?

**SourceMod version:** 1.10.0.6510
**MetaMod version:** 1.10.0-dev+1144
**DHooks version:** 2.2.0-detours17

Sorry for late reply! The notification is broken on GitHub so I didn't noticed your reply in time ;-;
Here is the version list!

**Comment by ldesgoui** [comment]
Could you inspect the contents of tf2-comp-fixes.smx in your installation against https://github.com/ldesgoui/tf2-comp-fixes/blob/updater/plugins/tf2-comp-fixes.smx? I suspect the file was mishandled during installation
It seems to work fine in other servers

**Comment by RoonMoonlight** [comment]
> Could you inspect the contents of tf2-comp-fixes.smx in your installation against https://github.com/ldesgoui/tf2-comp-fixes/blob/updater/plugins/tf2-comp-fixes.smx? I suspect the file was mishandled during installation
> It seems to work fine in other servers

Now I reinstalled it again but now another error happens:
```
L 09/02/2021 - 03:22:11: [SM] Exception reported: The server's operating system is not supported
L 09/02/2021 - 03:22:11: [SM] Blaming: tf2-comp-fixes.smx
L 09/02/2021 - 03:22:11: [SM] Call stack trace:
L 09/02/2021 - 03:22:11: [SM]   [0] SetFailState
L 09/02/2021 - 03:22:11: [SM]   [1] Line 55, addons/sourcemod/scripting/tf2-comp-fixes.sp::OnPluginStart
[SM] Plugin tf2-comp-fixes.smx failed to reload: Error detected in plugin startup (see error logs).
```

I'm using Ubuntu 20.04.3 LTS

**Comment by RoonMoonlight** [comment]
Okay it worked, I removed the existing gamedata file and I made new one then pasted the components of gamedata file

Now it works properly!
Thanks for the solution :)
