### ISSUE TITLE
Deprecate Windows Support

### ISSUE THREAD

**Issue by ldesgoui** [ldesgoui/tf2-comp-fixes#72]
Those are not good platforms and you should not host servers on them
Sorry not sorry :)

**Comment by sapphonie** [comment]
FTR, most managed NFOServers run on Windows, I believe

**Comment by ldesgoui** [comment]
Hearing that another popular provider, Swiftnode, also runs Windows servers.

I'll make this clear that I would rather operate as a server provider, even at a loss, than have to guarantee support for Windows.
