### ISSUE TITLE
If the game is paused, switching mediguns in spawn allows you to transfer the ubercharge

### ISSUE THREAD

**Issue by TheBv** [ldesgoui/tf2-comp-fixes#73]
Quick video demonstrating the issue: https://www.youtube.com/watch?v=C45ccmmMoEk
I've recorded this using the old version of the medigun-uber restore plugins but it's also an issue for this implementation.

Should be as simple as making sure that the "[medigun id](https://github.com/ldesgoui/tf2-comp-fixes/blob/77a7b8469765706877ea7345889fd44ec220a720/scripting/tf2-comp-fixes/fix-post-pause-state.sp#L47)" is the same when restoring the uber.

**Comment by ldesgoui** [comment]
Nice find, thank you

**Comment by ldesgoui** [comment]
Fixed in master, thank you for the report
