### ISSUE TITLE
Self Reflect Damage Fix Not Working

### ISSUE THREAD

**Issue by GreySux** [ldesgoui/tf2-comp-fixes#81]
] rcon sm plugins reload tf2-comp-fixes
L 01/13/2022 - 18:52:10: [SM] Exception reported: Failed to create detour for CTFFlameThrower::DeflectEntity
L 01/13/2022 - 18:52:10: [SM] Blaming: tf2-comp-fixes.smx
L 01/13/2022 - 18:52:10: [SM] Call stack trace:
L 01/13/2022 - 18:52:10: [SM]   [0] SetFailState
L 01/13/2022 - 18:52:10: [SM]   [1] Line 91, addons/sourcemod/scripting/tf2-comp-fixes/common.sp::CheckedDHookCreateFromConf
L 01/13/2022 - 18:52:10: [SM]   [2] Line 4, addons/sourcemod/scripting/tf2-comp-fixes/fix-reflect-self-damage.sp::FixReflectSelfDamage_Setup
L 01/13/2022 - 18:52:10: [SM]   [3] Line 78, addons/sourcemod/scripting/tf2-comp-fixes.sp::OnPluginStart
[SM] Plugin tf2-comp-fixes.smx failed to reload: Error detected in plugin startup (see error logs).
[SM] Plugin tf2-comp-fixes.smx reloaded successfully.

Not sure why this happens. Dhooks is fully installed and I don't know how else to fix the issue.

**Comment by ldesgoui** [comment]
Is your server running on Windows?

**Comment by GreySux** [comment]
> 

No, it is on Linux

**Comment by ldesgoui** [comment]
Is the gamedata file up to date?

**Comment by GreySux** [comment]
It should be. Is there a way I can check?

**Comment by ldesgoui** [comment]
I guess you could check whether "DeflectEntity" appears 5 times in the file?

**Comment by GreySux** [comment]
Yes it does.

**Comment by ldesgoui** [comment]
I don't really see how this could be happening. Which version have you installed?

**Comment by ldesgoui** [comment]
Re-open if you still need help with this
