### ISSUE TITLE
projectiles_collide_with_cylinders cannot break stickies

### ISSUE THREAD

**Issue by iBoonie** [ldesgoui/tf2-comp-fixes#83]
If you have `projectiles_collide_with_cylinders` enabled, the enemy team cannot break stickies with bullets. As soon as you turn that off everything is fine. This happens on v1.16.5 & .6, so i'm guessing it started from v1.16.0 where you first introduced it, but have not tested that far back.

I also get this dumped every now and then.
> L 01/16/2022 - 18:27:12: [SM] Exception reported: Client 4 is not in game
> L 01/16/2022 - 18:27:12: [SM] Blaming: tf2-comp-fixes.smx
> L 01/16/2022 - 18:27:12: [SM] Call stack trace:
> L 01/16/2022 - 18:27:12: [SM]   [0] IsPlayerAlive
> L 01/16/2022 - 18:27:12: [SM]   [1] Line 35, addons/sourcemod/scripting/tf2-comp-fixes/projectiles-collide-with-cylinders.sp::Detour_PassServerEntityFilter

**Comment by ldesgoui** [comment]
Thanks for the report, I will investigate this weekend.

**Comment by sapphonie** [comment]
Any updates on this? It's still an issue

**Comment by ldesgoui** [comment]
Fixed in v1.16.9
